CREATE TABLE IF NOT EXISTS users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    email       VARCHAR(100) NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    password    VARCHAR(255) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    is_active   INTEGER,
    login_id    VARCHAR(50)  NOT NULL,
    role        VARCHAR(10)  NOT NULL,
    marketing_agreed BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_users_email    UNIQUE (email),
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT users_role_check  CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS products (
    product_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    description      VARCHAR(2000) NOT NULL,
    is_active        INTEGER,
    name             VARCHAR(100)  NOT NULL,
    product_category VARCHAR(50),
    stock_quantity   INTEGER       NOT NULL,
    naver_product_id VARCHAR(50),
    sub_category     VARCHAR(50),
    search_keyword   VARCHAR(50),
    image_url        VARCHAR(500),
    max_price        INTEGER,
    min_price        INTEGER,
    brand            VARCHAR(100),
    category2        VARCHAR(50),
    mall_name        VARCHAR(100),
    CONSTRAINT uk_naver_product_id UNIQUE (naver_product_id)
);

CREATE TABLE IF NOT EXISTS product_images (
    image_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url  VARCHAR(200) NOT NULL,
    sort_order INTEGER      NOT NULL,
    product_id BIGINT       NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE IF NOT EXISTS address (
    address_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_detail    VARCHAR(200) NOT NULL,
    is_default        BOOLEAN      NOT NULL,
    road_name_address VARCHAR(200) NOT NULL,
    user_id           BIGINT       NOT NULL,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS cart (
    cart_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   INTEGER NOT NULL,
    product_id BIGINT  NOT NULL,
    user_id    BIGINT  NOT NULL,
    CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_cart_user    FOREIGN KEY (user_id)    REFERENCES users    (user_id)
);

CREATE TABLE IF NOT EXISTS wishlist (
    wish_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT fk_wishlist_user    FOREIGN KEY (user_id)    REFERENCES users    (user_id)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date   TIMESTAMP(6)  NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    total_amount INTEGER       NOT NULL,
    user_id      BIGINT        NOT NULL,
    CONSTRAINT fk_orders_user   FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT orders_status_check CHECK (status IN ('결제완료', '배송중', '완료', '취소'))
);

CREATE TABLE IF NOT EXISTS order_detail (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity      INTEGER NOT NULL,
    unit_price    INTEGER NOT NULL,
    order_id      BIGINT  NOT NULL,
    product_id    BIGINT  NOT NULL,
    CONSTRAINT fk_order_detail_order   FOREIGN KEY (order_id)   REFERENCES orders   (order_id),
    CONSTRAINT fk_order_detail_product FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE IF NOT EXISTS coupons (
    coupon_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount_type    VARCHAR(20)  NOT NULL,
    discount_value   INTEGER      NOT NULL,
    expired_at       TIMESTAMP(6) NOT NULL,
    min_order_amount INTEGER      NOT NULL,
    CONSTRAINT coupons_discount_type_check CHECK (discount_type IN ('정액', '정률'))
);

CREATE TABLE IF NOT EXISTS user_coupons (
    user_coupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_used        BOOLEAN      NOT NULL,
    used_at        TIMESTAMP(6),
    coupon_id      BIGINT       NOT NULL,
    user_id        BIGINT       NOT NULL,
    CONSTRAINT fk_user_coupons_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (coupon_id),
    CONSTRAINT fk_user_coupons_user   FOREIGN KEY (user_id)   REFERENCES users   (user_id)
);

CREATE TABLE IF NOT EXISTS event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    description VARCHAR(255),
    event_name  VARCHAR(255) NOT NULL,
    is_active   BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS event_field (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    field_name  VARCHAR(255) NOT NULL,
    field_type  VARCHAR(255) NOT NULL,
    is_required BOOLEAN      NOT NULL,
    event_id    BIGINT       NOT NULL,
    CONSTRAINT fk_event_field_event FOREIGN KEY (event_id) REFERENCES event (id)
);

CREATE TABLE IF NOT EXISTS campaign (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    batch_cycle             INTEGER,
    campaign_goal_type      VARCHAR(255) NOT NULL,
    campaign_name           VARCHAR(255) NOT NULL,
    campaign_type           VARCHAR(255) NOT NULL,
    created_by              VARCHAR(255),
    customer_segment        VARCHAR(255) NOT NULL,
    description             VARCHAR(255),
    ended_at                TIMESTAMP(6) NOT NULL,
    is_duplicate            BOOLEAN      NOT NULL,
    started_at              TIMESTAMP(6) NOT NULL,
    status                  VARCHAR(255) NOT NULL,
    filter_logical_operator VARCHAR(255),
    CONSTRAINT campaign_campaign_goal_type_check      CHECK (campaign_goal_type      IN ('EARLY_RETENTION', 'CHURN_PREVENTION', 'REPURCHASE')),
    CONSTRAINT campaign_campaign_type_check           CHECK (campaign_type           IN ('TRIGGERED', 'BATCH')),
    CONSTRAINT campaign_customer_segment_check        CHECK (customer_segment        IN ('VIP', 'NEW', 'GENERAL', 'DORMANT', 'ALL')),
    CONSTRAINT campaign_filter_logical_operator_check CHECK (filter_logical_operator IN ('AND', 'OR')),
    CONSTRAINT campaign_status_check                  CHECK (status                  IN ('PENDING', 'IN_PROGRESS', 'PAUSED', 'ENDED'))
);

CREATE TABLE IF NOT EXISTS campaign_filter (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator       VARCHAR(255) NOT NULL,
    period_days    INTEGER      NOT NULL,
    value          VARCHAR(255) NOT NULL,
    campaign_id    BIGINT       NOT NULL,
    event_field_id BIGINT       NOT NULL,
    CONSTRAINT fk_campaign_filter_campaign    FOREIGN KEY (campaign_id)    REFERENCES campaign    (id),
    CONSTRAINT fk_campaign_filter_event_field FOREIGN KEY (event_field_id) REFERENCES event_field (id)
);
