INSERT INTO event (id, event_name, description, is_active) VALUES
(1,  'purchase_button_click', '사용자가 상품 구매 버튼을 클릭했을 때 발생하는 이벤트',                   true),
(2,  'wishlist_cart_action',  '사용자가 상품을 찜하거나 장바구니에 추가 또는 삭제할 때 발생하는 이벤트', true),
(3,  'coupon_received',       '사용자가 쿠폰을 발급받을 때 발생하는 이벤트',                             true),
(4,  'coupon_used',           '사용자가 결제 시 쿠폰을 적용할 때 발생하는 이벤트',                       true),
(5,  'ad_click',              '사용자가 광고 배너 또는 광고 상품을 클릭할 때 발생하는 이벤트',           true),
(6,  'search_button_click',   '사용자가 검색어를 입력하고 검색을 실행할 때 발생하는 이벤트',             true),
(7,  'page_view',             '사용자가 특정 페이지에 진입할 때 발생하는 이벤트',                        true),
(8,  'product_detail_view',   '사용자가 특정 상품의 상세 페이지로 이동할 때 발생하는 이벤트',            true),
(9,  'review_submit_click',   '사용자가 리뷰 작성 후 등록 버튼을 클릭할 때 발생하는 이벤트',             true),
(10, 'point_earned',          '사용자에게 포인트가 적립될 때 발생하는 이벤트',                           true),
(11, 'point_used',            '사용자가 결제 시 포인트를 차감하여 사용할 때 발생하는 이벤트',            false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO event_field (id, event_id, field_name, field_type, is_required, description) VALUES
(1,  1,  'approvedAmount', 'NUMBER',   true,  '결제 승인된 최종 금액 (원 단위)'),
(2,  1,  'productName',    'STRING',   true,  '구매한 상품의 이름'),
(3,  1,  'productId',      'STRING',   true,  '상품 고유 식별자'),
(4,  1,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(5,  2,  'productName',    'STRING',   true,  '찜/장바구니 대상 상품명'),
(6,  2,  'productId',      'STRING',   true,  '상품 고유 식별자'),
(7,  2,  'actionType',     'STRING',   true,  'add / remove 구분값'),
(8,  2,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(9,  3,  'couponCode',     'STRING',   true,  '발급된 쿠폰의 고유 코드'),
(10, 3,  'discountAmount', 'NUMBER',   true,  '쿠폰 적용 시 할인되는 금액 (원 단위)'),
(11, 3,  'expiryDate',     'DATE',     false, '쿠폰 유효 만료 날짜 — 만료율 분석에 유용'),
(12, 3,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(13, 4,  'couponCode',     'STRING',   true,  '사용된 쿠폰의 고유 코드'),
(14, 4,  'discountAmount', 'NUMBER',   true,  '실제 적용된 할인 금액 (원 단위)'),
(15, 4,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(16, 5,  'productName',    'STRING',   true,  '광고된 상품명'),
(17, 5,  'productId',      'STRING',   true,  '광고 상품 고유 식별자'),
(18, 5,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(19, 6,  'searchKeyword',  'STRING',   true,  '사용자가 입력한 검색어'),
(20, 6,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(21, 7,  'pageName',       'STRING',   true,  '진입한 페이지의 이름 또는 경로'),
(22, 7,  'dwellTime',      'TIME',     true,  '페이지 체류시간 (초 단위)'),
(23, 7,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(24, 8,  'productName',    'STRING',   true,  '조회한 상품명'),
(25, 8,  'productId',      'STRING',   true,  '상품 고유 식별자'),
(26, 8,  'dwellTime',      'TIME',     true,  '상세 페이지 체류시간 (초 단위)'),
(27, 8,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(28, 9,  'reviewRating',   'NUMBER',   true,  '사용자가 부여한 별점 (1~5 정수)'),
(29, 9,  'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(30, 10, 'earnedPoints',   'NUMBER',   true,  '이번에 적립된 포인트 수'),
(31, 10, 'earnReason',     'STRING',   true,  '적립 원인 (구매완료 / 리뷰작성 / 출석 등)'),
(32, 10, 'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간'),
(33, 11, 'usedPoints',     'NUMBER',   true,  '이번 거래에서 사용된 포인트 수'),
(34, 11, 'eventTimestamp', 'DATETIME', true,  '해당 이벤트 발생 시간')
ON CONFLICT (id) DO NOTHING;
